### ISSUE TITLE
VirtualFile.get_file_size() returns ValueError if file does not exists?

### ISSUE THREAD

**Issue by joachimmetz** [ydkhatri/UnifiedLogReader#27]
VirtualFile.get_file_size() returns ValueError if file does not exists?

```
======================================================================
ERROR: testGetFileSize (virtual_file.VirtualFileTest)
Tests the get_file_size function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "UnifiedLogReader/tests/virtual_file.py", line 24, in testGetFileSize
    file_size = file_entry.get_file_size()
  File "UnifiedLogReader/UnifiedLog/virtual_file.py", line 45, in get_file_size
    raise ValueError('File pointer was invalid. File must be opened before calling get_file_size()')
ValueError: File pointer was invalid. File must be opened before calling get_file_size()
```

@ydkhatri is this the intended behavior? IMHO an IOError('No such file') or equiv would be more clear.

**Comment by ydkhatri** [comment]
Yes, you can change it to that. I didn't care as long as it was some kind of exception!

**Comment by ydkhatri** [comment]
I have made the change in last commit. https://github.com/ydkhatri/UnifiedLogReader/commit/d48f0a54a404642333ab6e89a177e4c09c495042.
